version: '3.8'

services:
  customers:
   build: ./customers
   ports: 
     - "8081:8080"
   environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/devsu
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root123
   depends_on:
      - db

  accounts:
   build: ./accounts
   ports:
    - "8082:8080"   
   environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/devsu
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root123 
   depends_on:
      - db
  
  db:
   image: mysql:8.0
   ports:
    - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root123
     MYSQL_DATABASE: devsu
   volumes:
    - db_data:/var/lib/mysql
    - ./db-init:/docker-entrypoint-initdb.d
  
   healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: